# Generated by Django 3.0.3 on 2020-02-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=30)),
                ('apt_suite', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=50)),
                ('office_phone', models.CharField(max_length=50)),
            ],
        ),
    ]
